# Rust edition for parsing and formatting
edition = "2024"

# Maximum line width
max_width = 100

# Use heuristics to break items less aggressively
use_small_heuristics = "Max"

# Use field init shorthand if possible
use_field_init_shorthand = true
