name: Run Linters

on:
  workflow_call:

jobs:
  run-linters:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Rust Environment
        uses: ./.github/actions/setup
        with:
          components: rustfmt,clippy
          install-mise: 'true'
          mise-tools: just

      - name: Run Linters
        run: mise exec -- just check
        shell: bash
