name: Run Linters

on:
  workflow_call:

jobs:
  run-linters:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Rust Environment
        uses: ./.github/actions/setup
        with:
          components: rustfmt,clippy

      - name: Run Linters
        run: |
          cargo fmt --check
          cargo clippy --all-targets --all-features -- -D warnings
        shell: bash
