name: Run Tests

on:
  workflow_call:

jobs:
  test:
    name: Run all tests
    runs-on: ubuntu-latest
    env:
      RUST_BACKTRACE: 1

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup environment
        uses: ./.github/actions/setup

      - name: Run all tests
        run: RUST_TEST_THREADS=1 cargo test --all-targets --all-features